--liquibase formatted sql

--changeset desou:001-baseline
CREATE SCHEMA IF NOT EXISTS ${appSchema};

CREATE TABLE ${appSchema}.usuarios
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(255) NOT NULL,
    nome_social VARCHAR(255),
    username    VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    cpf         VARCHAR(255) NOT NULL,
    papel       VARCHAR(255) NOT NULL,
    status      BOOLEAN      NOT NULL,
    bloqueado   BOOLEAN,
    curso       VARCHAR(255),
    matricula   VARCHAR(255),
    foto_perfil VARCHAR(255),
    CONSTRAINT uk_usuarios_username UNIQUE (username),
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT uk_usuarios_cpf UNIQUE (cpf),
    CONSTRAINT uk_usuarios_matricula UNIQUE (matricula),
    CONSTRAINT ck_usuarios_papel CHECK (papel IN ('ADMIN', 'ALUNO', 'BOLSISTA')),
    CONSTRAINT ck_usuarios_curso CHECK (curso IS NULL OR curso IN ('IA', 'CC', 'SI', 'RC', 'ES', 'EC', 'DD'))
);

CREATE TABLE ${appSchema}.estoque
(
    id                    UUID PRIMARY KEY,
    version               BIGINT,
    nome                  VARCHAR(255) NOT NULL,
    quantidade            INTEGER      NOT NULL,
    quantidade_disponivel INTEGER      NOT NULL,
    tipo                  VARCHAR(255) NOT NULL,
    is_ativado            BOOLEAN,
    CONSTRAINT ck_estoque_tipo CHECK (tipo IN ('EQUIPAMENTO', 'COMPONENTE')),
    CONSTRAINT ck_estoque_quantidade CHECK (quantidade >= 0),
    CONSTRAINT ck_estoque_disponivel CHECK (quantidade_disponivel >= 0 AND quantidade_disponivel <= quantidade)
);

CREATE TABLE ${appSchema}.pedidos
(
    id                  UUID PRIMARY KEY,
    version             BIGINT,
    codigo_pedido       VARCHAR(255)                   NOT NULL,
    feedback            TEXT,
    solicitante_id      BIGINT                         NOT NULL,
    aprovador_id        BIGINT,
    finalizador_id      BIGINT,
    data_solicitacao    TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    data_aprovacao      TIMESTAMP(6) WITHOUT TIME ZONE,
    data_finalizado     TIMESTAMP(6) WITHOUT TIME ZONE,
    data_atualizacao    TIMESTAMP(6) WITHOUT TIME ZONE,
    status              VARCHAR(255)                   NOT NULL,
    emprestimo_especial BOOLEAN,
    hash                VARCHAR(255),
    CONSTRAINT uk_pedidos_codigo UNIQUE (codigo_pedido),
    CONSTRAINT ck_pedidos_status CHECK (status IN ('PENDENTE', 'APROVADO', 'REJEITADO', 'FINALIZADO', 'CANCELADO')),
    CONSTRAINT fk_pedidos_solicitante FOREIGN KEY (solicitante_id) REFERENCES ${appSchema}.usuarios (id),
    CONSTRAINT fk_pedidos_aprovador FOREIGN KEY (aprovador_id) REFERENCES ${appSchema}.usuarios (id),
    CONSTRAINT fk_pedidos_finalizador FOREIGN KEY (finalizador_id) REFERENCES ${appSchema}.usuarios (id)
);

CREATE TABLE ${appSchema}.itens_pedido
(
    id              UUID PRIMARY KEY,
    pedido_id       UUID    NOT NULL,
    estoque_id      UUID    NOT NULL,
    quantidade_item INTEGER NOT NULL,
    CONSTRAINT ck_itens_pedido_quantidade CHECK (quantidade_item > 0),
    CONSTRAINT fk_itens_pedido_pedido FOREIGN KEY (pedido_id) REFERENCES ${appSchema}.pedidos (id),
    CONSTRAINT fk_itens_pedido_estoque FOREIGN KEY (estoque_id) REFERENCES ${appSchema}.estoque (id)
);

CREATE TABLE ${appSchema}.bloqueios
(
    id                 UUID PRIMARY KEY,
    usuario_id         BIGINT                         NOT NULL,
    admin_block_id     BIGINT                         NOT NULL,
    admin_unblock_id   BIGINT,
    motivo_desbloqueio TEXT,
    motivo_bloqueio    TEXT                           NOT NULL,
    data_bloqueio      TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    data_desbloqueio   TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT fk_bloqueios_usuario FOREIGN KEY (usuario_id) REFERENCES ${appSchema}.usuarios (id),
    CONSTRAINT fk_bloqueios_admin_block FOREIGN KEY (admin_block_id) REFERENCES ${appSchema}.usuarios (id),
    CONSTRAINT fk_bloqueios_admin_unblock FOREIGN KEY (admin_unblock_id) REFERENCES ${appSchema}.usuarios (id)
);

--rollback DROP SCHEMA ${appSchema} CASCADE;
