stages:
  - build
  - deploy

build_frontend:
  stage: build
  image: node:20
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 day

serve_backend:
  stage: deploy
  image: node:20
  script:
    - cd frontend
    - npm install
    - npm run server
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'

pages:
  stage: deploy
  image: alpine
  dependencies:
    - build_frontend
  script:
    - mv frontend/dist public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'

