server:
  port: 8090

sigaa:
  base: http://almoxarifadoec.quixada.ufc.br:3000/sigaa

api:
  security:
    token:
        secret: bagr3SuhjwjEIbdD5Y+e94wuM60JGa/99TDzY6visSw=

spring:
  application:
    name: almoxarifado_backend

  profiles:
    default: dev

  mvc:
    servlet:
      path: /api

  jpa:
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 6MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: desousafelipe10@gmail.com
    password: oymv wnea gfne dbuc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-operation-id: true
    doc-expansion: list
  api-docs:
    path: /v3/api-docs
  show-actuator: false

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS}){faint} %clr([%-5level]) %clr(${AEC:- }){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{36}){cyan} %clr([%file:%line]){green} %clr(:){faint} %m%n"
