server:
  port: 8090

spring:

  config:
    import: "optional:file:.env[.properties], optional:file:../backend/.env[.properties], optional:file:../.env[.properties], optional:file:../../.env[.properties]"

  application:
    name: almoxarifado_backend


  mvc:
    servlet:
      path: /api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
          jwk-set-uri: ${JWT_JWK_SET_URI}

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 6MB

  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: ${EMAIL_HOST}

keycloak:
  root:
    url: ${KEYCLOAK_ROOT_URL}

  admin:
    base-url: ${KEYCLOAK_ADMIN_BASE_URL}
    realm: ${KEYCLOAK_ADMIN_REALM}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
    roles-client-id: ${KEYCLOAK_ADMIN_ROLES_CLIENT_ID}
    roles-client-uuid: ${KEYCLOAK_ADMIN_ROLES_CLIENT_UUID}
    role-admin-id: ${KEYCLOAK_ADMIN_ROLE_ADMIN_ID}
    role-bolsista-id: ${KEYCLOAK_ADMIN_ROLE_BOLSISTA_ID}
    default-password: ${KEYCLOAK_ADMIN_DEFAULT_PASSWORD}

  user:
    client-id: ${KEYCLOAK_USER_CLIENT_ID}
    client-secret: ${KEYCLOAK_USER_CLIENT_SECRET}

jwt:
  auth:
    converter:
      resource-id: ${JWT_RESOURCE_ID}
      principle-attribute: ${JWT_PRINCIPLE_ATTRIBUTE}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-operation-id: true
    doc-expansion: list
  api-docs:
    path: /v3/api-docs
  show-actuator: false

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS}){faint} %clr([%-5level]) %clr(${AEC:- }){magenta} %clr([%15.15t]){faint} %clr(%-40.40logger{36}){cyan} %clr([%file:%line]){green} %clr(:){faint} %m%n"
